"""Generates the animated attention-arc banner used at the top of the profile README.

The banner is an arc diagram of one attention head reading a 20-token sequence:
dots on a baseline are tokens, arcs above are attention weights. A query sweeps
left to right and its edges draw themselves outward from the active token, hold,
then fade, so at any moment ~3 queries overlap as a cascade.

Everything animates through CSS *inside* the SVG. That is the one animation
technique that survives GitHub: README <script> and <style> are stripped by the
HTML sanitizer, but an SVG referenced as an image is rendered by the browser as
an image, where declarative CSS animation still runs. The same sandbox blocks
external requests, so the type stack has to be fonts already on the machine --
no webfonts, hence GitHub's own ui-monospace stack rather than Space Mono.

Four files, one per (theme, motion) pair. Both axes have to be resolved by the
README rather than by the SVG:

  * Theme, because an SVG loaded via <img> gets no signal about the page
    background it is sitting on.
  * Motion, because `@media (prefers-reduced-motion: reduce)` *inside* an
    image-mode SVG does not track the viewer's actual preference -- measured in
    Chromium, it matched even with the host page reporting no-preference, which
    froze the animation for everyone. Selecting a still file from the README's
    <picture> puts that query back in the page context, where it works.

Run:  python tools/build_banner.py
"""

import pathlib
import random

W, H = 880, 260
N_TOKENS = 20
X0, X1 = 48, 832          # first and last token centre
BASE_Y = 228              # the token baseline; arcs bulge above it
MAX_ARC_H = 98
LOOP = 12.0               # seconds for the query to cross the whole sequence

# How much of each element's timeline is spent visible. The stagger delay is
# what walks that window across the sequence.
SWEEP_KEYFRAMES = """
    0%   { stroke-dashoffset: 100; opacity: 0; }
    1%   { stroke-dashoffset: 100; opacity: var(--w); }
    6%   { stroke-dashoffset: 0;   opacity: var(--w); }
    11%  { stroke-dashoffset: 0;   opacity: var(--w); }
    16%  { stroke-dashoffset: 0;   opacity: 0; }
    100% { stroke-dashoffset: 0;   opacity: 0; }
"""

THEMES = {
    "light": dict(ink="#1a1a1a", muted="#8a8a8a", rule="#e6e6e6"),
    "dark": dict(ink="#e6edf3", muted="#8b949e", rule="#30363d"),
}

MONO = ("ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, "
        "'Liberation Mono', monospace")


def token_x(i):
    return X0 + (X1 - X0) * i / (N_TOKENS - 1)


def edges():
    """Attention edges as (query, key, weight), weight in 0..1.

    Shaped to look like a real head rather than noise: a two-token local window
    carries most of the mass, every query keeps a thin edge back to token 0 (the
    attention sink that shows up in practically every trained transformer), and
    one long-range edge stops the picture from being purely banded.

    Deliberately sparse. An earlier pass drew a +/-3 window, and 143 arcs read as
    a decorative scalloped fence rather than as attention.
    """
    rng = random.Random(7)   # fixed seed: regenerating must not churn the diff
    out = []
    for q in range(N_TOKENS):
        for off in (-2, -1, 1, 2):
            k = q + off
            if 0 <= k < N_TOKENS:
                w = 0.92 if abs(off) == 1 else 0.55
                out.append((q, k, w * rng.uniform(0.8, 1.0)))

        if q > 2:
            out.append((q, 0, rng.uniform(0.28, 0.46)))

        k = rng.randrange(N_TOKENS)
        if abs(k - q) > 2:
            out.append((q, k, rng.uniform(0.18, 0.42)))
    return out


def arc_path(q, k):
    """Path running query -> key, always bulging above the baseline.

    Direction matters: because stroke-dashoffset draws a path from its start,
    beginning at the query makes each edge appear to radiate out of the token
    that is currently active.
    """
    xq, xk = token_x(q), token_x(k)
    dx = abs(xk - xq)
    span = X1 - X0
    rx = dx / 2
    ry = 12 + (MAX_ARC_H - 12) * (dx / span) ** 0.62
    sweep = 1 if xk > xq else 0
    return (f"M{xq:.1f},{BASE_Y} A{rx:.1f},{ry:.1f} 0 0,{sweep} "
            f"{xk:.1f},{BASE_Y}")


def build(theme_name, animated):
    t = THEMES[theme_name]
    step = LOOP / N_TOKENS

    p = []
    p.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'width="{W}" height="{H}" role="img" '
        f'aria-label="michael tarekegn - math and ml research: '
        f'an attention arc diagram">'
    )
    p.append("<!-- generated by tools/build_banner.py - edit that, not this -->")

    if animated:
        motion = f"""
  .arc  {{ opacity: 0; animation: sweep {LOOP}s linear infinite; }}
  .dot circle {{ animation: pulse {LOOP}s linear infinite; }}
  .tick {{ opacity: 0; animation: tick {LOOP}s linear infinite; }}

  @keyframes sweep {{{SWEEP_KEYFRAMES}  }}
  @keyframes pulse {{
    0%   {{ transform: scale(1);   fill-opacity: .22; }}
    3%   {{ transform: scale(1.9); fill-opacity: 1; }}
    12%  {{ transform: scale(1.9); fill-opacity: 1; }}
    20%  {{ transform: scale(1);   fill-opacity: .22; }}
    100% {{ transform: scale(1);   fill-opacity: .22; }}
  }}
  @keyframes tick {{
    0%   {{ opacity: 0; }}
    3%   {{ opacity: .55; }}
    12%  {{ opacity: .55; }}
    20%  {{ opacity: 0; }}
    100% {{ opacity: 0; }}
  }}"""
    else:
        # Still frame for reduced-motion readers: the same diagram at rest.
        # Only every fourth query is kept, which leaves five separated fans.
        # Keeping more is not a middle ground -- because each query reaches
        # two tokens either side, every third query already spans every
        # adjacent pair and the result collapses back into a solid fence.
        motion = """
  .arc  { opacity: 0; stroke-dashoffset: 0; }
  .arc.rest { opacity: calc(var(--w) * .62); }
  .dot circle { fill-opacity: .3; }
  .tick { opacity: 0; }"""

    p.append(f"""<style>
  .t {{ font-family: {MONO}; }}
  .name {{ font-size: 27px; fill: {t['ink']}; letter-spacing: .5px; }}
  .sub  {{ font-size: 12.5px; fill: {t['muted']}; letter-spacing: .3px; }}
  .cap  {{ font-size: 9.5px; fill: {t['muted']}; letter-spacing: 1.1px; }}
  .rule {{ stroke: {t['rule']}; stroke-width: 1; }}
  .arc  {{ fill: none; stroke: {t['ink']}; stroke-linecap: round;
          stroke-dasharray: 100; stroke-dashoffset: 100; }}
  .dot  {{ fill: {t['ink']}; fill-opacity: .22; }}
  .tick {{ stroke: {t['ink']}; stroke-width: 1; }}
{motion}
</style>""")

    p.append('<text class="t name" x="48" y="52">michael tarekegn</text>')
    p.append(
        '<text class="t sub" x="48" y="76">math &amp; ml research '
        '&#183; self-attention &#183; physics-informed neural networks</text>'
    )
    p.append(f'<line class="rule" x1="48" y1="{BASE_Y}" x2="832" y2="{BASE_Y}"/>')

    p.append("<g>")
    for q, k, w in edges():
        rest = " rest" if (not animated and q % 4 == 0) else ""
        p.append(
            f'<path class="arc{rest}" pathLength="100" d="{arc_path(q, k)}" '
            f'stroke-width="{0.65 + w * 0.95:.2f}" '
            f'style="--w:{0.16 + w * 0.72:.2f};'
            f'animation-delay:{q * step:.2f}s"/>'
        )
    p.append("</g>")

    for i in range(N_TOKENS):
        x, delay = token_x(i), i * step
        p.append(
            f'<g class="dot" transform="translate({x:.1f},{BASE_Y})">'
            f'<circle r="1.9" style="animation-delay:{delay:.2f}s"/></g>'
        )
        p.append(
            f'<line class="tick" x1="{x:.1f}" y1="{BASE_Y + 6}" '
            f'x2="{x:.1f}" y2="{BASE_Y + 13}" '
            f'style="animation-delay:{delay:.2f}s"/>'
        )

    p.append(
        f'<text class="t cap" x="832" y="{BASE_Y + 30}" text-anchor="end">'
        f'one head &#183; {N_TOKENS} tokens</text>'
    )
    p.append("</svg>")
    return "\n".join(p) + "\n"


if __name__ == "__main__":
    root = pathlib.Path(__file__).resolve().parent.parent
    for theme in THEMES:
        for animated in (True, False):
            suffix = "" if animated else "-still"
            f = root / "assets" / f"attention-{theme}{suffix}.svg"
            f.write_text(build(theme, animated), encoding="utf-8")
            print(f"wrote {f.relative_to(root)}  ({f.stat().st_size:,} bytes)")
